"""Idempotently seed the five canonical LLD questions."""
import asyncio
from sqlalchemy import delete, select
from app.core.database import session_factory
from app.models.problem import Problem

PROBLEMS = [
    {"slug":"parking-lot-system","title":"Parking Lot System","difficulty":"Easy","prerequisites":["OOP","Interfaces","Strategy Pattern"],"description":"Design a parking lot that supports multiple floors and vehicle types. Vehicles should be assigned suitable parking spots and charged based on parking duration and vehicle type.","sample_scenario":"A car enters, receives a ticket, gets a spot, parks for 3 hours, and exits after payment.","requirements":["Support multiple parking floors and spots.","Support car, bike, and truck vehicles.","Allocate and release parking spots.","Generate parking tickets.","Calculate parking fees.","Support different pricing strategies."],"constraints":["Multiple vehicles may enter concurrently.","Spot allocation must not assign the same spot twice."],"hints":["Separate parking, allocation, ticketing, and pricing responsibilities.","Consider Strategy for allocation and pricing."],"expected_concepts":["SOLID","Strategy","composition","interfaces","concurrency"],"evaluation_criteria":["Clear responsibilities","Good abstractions","Correct relationships","Extensible pricing/allocation","Handles concurrency and edge cases"],"estimated_time":45,"patterns":["Strategy"]},
    {"slug":"elevator-system","title":"Elevator System","difficulty":"Easy","prerequisites":["OOP","State/Strategy Pattern"],"description":"Design an elevator system for a building with multiple elevators and floors.","sample_scenario":"A user requests an elevator from floor 7 to floor 15. The system selects an appropriate elevator and processes the request.","requirements":["Multiple elevators and floors.","Internal and external requests.","Select the best elevator.","Move elevators between floors.","Track elevator state and direction.","Handle concurrent requests."],"constraints":["Avoid conflicting elevator assignments.","Requests may arrive simultaneously."],"hints":["Separate request handling, elevator selection, and elevator movement.","Consider Strategy for elevator selection."],"expected_concepts":["Strategy","State","SOLID","concurrency"],"evaluation_criteria":["Good domain modeling","Appropriate abstractions","Extensible selection logic","Correct state handling","Concurrency considerations"],"estimated_time":45,"patterns":["Strategy","State"]},
    {"slug":"online-food-ordering","title":"Online Food Ordering System","difficulty":"Medium","prerequisites":["OOP","SOLID","Strategy","Observer"],"description":"Design a food ordering platform where users browse restaurants, create orders, pay, and track order status.","sample_scenario":"A user selects items from a restaurant, places an order, pays, and receives status updates until delivery.","requirements":["Users can browse restaurants and menus.","Create and modify orders before confirmation.","Support multiple payment methods.","Track order lifecycle.","Notify users when order status changes.","Calculate discounts and delivery charges."],"constraints":["Payment and notification implementations should be replaceable.","Order state transitions must be valid."],"hints":["Use Strategy for payment/discount logic.","Use Observer for order status notifications."],"expected_concepts":["Strategy","Observer","State","SOLID"],"evaluation_criteria":["Separation of concerns","Correct order lifecycle","Extensible payment/discount design","Notification abstraction","Edge-case handling"],"estimated_time":60,"patterns":["Strategy","Observer","State"]},
    {"slug":"rate-limiter","title":"Rate Limiter","difficulty":"Medium","prerequisites":["OOP","concurrency","basic distributed systems"],"description":"Design a rate limiter that restricts how many requests a user or API client can make within a time window.","sample_scenario":"An API allows 100 requests per minute per user. The 101st request is rejected until capacity becomes available.","requirements":["Rate limit by user/API key.","Support configurable limits.","Allow requests or reject them.","Support multiple rate-limiting algorithms.","Be thread-safe.","Provide a way to inspect remaining capacity."],"constraints":["High concurrency.","Low latency.","The design should allow future distributed implementation."],"hints":["Define a RateLimiter interface.","Consider Token Bucket, Fixed Window, or Sliding Window strategies."],"expected_concepts":["Strategy","interfaces","concurrency","synchronization"],"evaluation_criteria":["Correct algorithm abstraction","Thread safety","Performance awareness","Extensibility","Clear trade-offs"],"estimated_time":45,"patterns":["Strategy"]},
    {"slug":"notification-system","title":"Notification System","difficulty":"Medium","prerequisites":["OOP","SOLID","Strategy","Observer"],"description":"Design a notification system that sends messages through multiple channels such as email, SMS, and push notifications.","sample_scenario":"A user's order is completed and the platform sends an email and push notification based on user preferences.","requirements":["Support email, SMS, and push channels.","Support user notification preferences.","Allow different message templates.","Support retries for failed delivery.","Allow new channels to be added without modifying core logic.","Track notification status."],"constraints":["Delivery providers may change.","Sending can be asynchronous."],"hints":["Use a NotificationChannel interface.","Use Strategy or Factory for channel selection.","Consider Observer/event-driven notification triggering."],"expected_concepts":["Strategy","Factory","Observer","SOLID","async processing"],"evaluation_criteria":["Extensibility","Provider abstraction","Clean separation of concerns","Retry/error handling","Appropriate design patterns"],"estimated_time":45,"patterns":["Strategy","Factory","Observer"]},
]

async def seed() -> None:
    async with session_factory() as session:
        # Remove only records created by the previous incomplete catalog seed.
        # Canonical records and unrelated future records are preserved.
        await session.execute(delete(Problem).where(Problem.slug.like("legacy-%")))
        for values in PROBLEMS:
            existing = await session.scalar(select(Problem).where(Problem.slug == values["slug"]))
            if existing:
                for key, value in values.items(): setattr(existing, key, value)
            else: session.add(Problem(**values))
        await session.commit()

if __name__ == "__main__": asyncio.run(seed())
